### ISSUE TITLE
希望增加在模拟器弹出页面崩溃时点击取消的功能

### ISSUE THREAD

**Issue by mobosa** [SpringCity-LaoYang/AutoXue-multiuser#12]
![84926544-2197ce00-b0fe-11ea-8822-85b0603c0181](https://user-images.githubusercontent.com/49510802/94466200-a44b2180-01f3-11eb-922c-801538d54b57.png)

**Comment by mobosa** [comment]
[https://user-images.githubusercontent.com/32977308/84926544-2197ce00-b0fe-11ea-8822-85b0603c0181.png](url)

**Comment by mobosa** [comment]
![Uploading 84926544-2197ce00-b0fe-11ea-8822-85b0603c0181.png…]()

**Comment by mobosa** [comment]
![84926544-2197ce00-b0fe-11ea-8822-85b0603c0181](https://user-images.githubusercontent.com/49510802/94466156-94334200-01f3-11eb-9e87-b0f1dabab6d7.png)

**Comment by SpringCity-LaoYang** [comment]
这个问题正在解决

**Comment by mobosa** [comment]
> 这个问题正在解决

感谢大佬
