### ISSUE TITLE
请问这是什么情况，大神

### ISSUE THREAD

**Issue by hbyilyzty** [SpringCity-LaoYang/AutoXue-multiuser#14]
D:\Software\xuexiqiangguo\AutoXue-multiuser-master
Appium.exe                    6832 Console                    1    252,584 K
Appium.exe                    9572 Console                    1     76,212 K
Appium.exe                   20228 Console                    1    266,632 K
Appium.exe                   16856 Console                    1     40,160 K
Nox.exe                      10264 Console                    1     78,528 K
C:\Users\Raker\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
本次学习以下账号：
[['18686868686', '123123123123']]
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
[INFO] 发现app已经登录，退出重新登录
[INFO] 刷分出现如下异常：    Message:

[INFO] 退出登录出现如下异常：    Message:

[ERROR] 找不到元素: //*[@text="取消"]
[INFO] 莫名其妙错误！
[INFO] app未登录
[INFO] app出错，返回上一层！
[INFO] 刷分出现如下异常：    Message:

[INFO] 退出登录出现如下异常：    Message:

[ERROR] 找不到元素: //*[@text="取消"]
[INFO] 莫名其妙错误！
[INFO] app未登录
[INFO] app出错，返回上一层！
[INFO] 刷分出现如下异常：    Message:

[INFO] 退出登录出现如下异常：    Message:

[ERROR] 找不到元素: //*[@text="取消"]
[INFO] 莫名其妙错误！
[INFO] app未登录
[INFO] app出错，返回上一层！
[INFO] 刷分出现如下异常：    Message:

[INFO] 退出登录出现如下异常：    Message:

[ERROR] 找不到元素: //*[@text="取消"]
[INFO] 莫名其妙错误！
[

**Comment by SpringCity-LaoYang** [comment]
是否是app退出了，如果是点击启动起来在等等。
