### ISSUE TITLE
这一版增加了争上游和双人对战功能，但多账号无法自动切换了。

### ISSUE THREAD

**Issue by zz803abc** [SpringCity-LaoYang/AutoXue-multiuser#22]
这一版增加了争上游和双人对战功能，但是只有第一个账号能刷分，无法自动切换到第二个，第三个账号刷分，即使第二个，第三个账号不需要做争上游和双人对战题，也还是无法自动切换。作者的思路是只允许第一个账号刷争上游，那也可以，请自动让第二个，第三个账号刷新闻，视频等，不刷争上游也行，但是现在不能自动切换。

此外，能不能添加争上游刷星星的功能！
现在是第一个账号如果争上游得满分后，不会再做争上游的题了。能不能改一下，即使争上游得了满分，也可以继续刷星星。

多谢，大佬！！

**Comment by SpringCity-LaoYang** [comment]
争上游别刷星星，星星多了你对手都是高星用户，你还想拿分吧。我限制的目的就是让争上游使用频率降下来，尽量克制，如果总是夺冠，就离被封杀差不多了。

**Comment by zz803abc** [comment]
> 争上游别刷星星，星星多了你对手都是高星用户，你还想拿分吧。我限制的目的就是让争上游使用频率降下来，尽量克制，如果总是夺冠，就离被封杀差不多了。

那只第一个账号刷争上游，刷完后，第二个，第三个账号顺序自动切换刷新闻，视频等，能实现吗？现在是第一个账号刷完新闻，视频，争上游后，不会自动切换到第二个，第三个账号。我现在的解决办法是：先用以前不带争上游的版本自动刷完三个账号的新闻，视频。然后，再用这个版本刷第一个账号的争上游，有点儿麻烦！！烦请大佬酌情考虑！！！

**Comment by SpringCity-LaoYang** [comment]
dev分支全部放开了，自己下载用吧。

**Comment by zz803abc** [comment]
> dev分支全部放开了，自己下载用吧。

感谢大佬！！

还有一个问题，就是可能阅读新闻压缩的时间太狠了，经常学不满分。差一分，然后继续学一篇吧，也仍然学不满分，建议大佬不用太在意压缩时间这个事儿，可以学的长一点儿，篇目多一点儿。
