### ISSUE TITLE
这是什么错误？dev分支的

### ISSUE THREAD

**Issue by zz803abc** [SpringCity-LaoYang/AutoXue-multiuser#29]
![image](https://user-images.githubusercontent.com/50546321/94988196-1cbc3480-059e-11eb-8ec2-0d8c1881672c.png)

**Comment by zz803abc** [comment]
搞清了，这是模拟器卡死了。

另外，大佬，还有一个问题，就是争上游答题次数到每日上限后，就会卡到达到上限的界面，无法退出，卡死 ，还请大佬研究解决，多谢!!

**Comment by gzh888666** [comment]
abd版本的问题！
