### ISSUE TITLE
老大，环境准备中的两张图片不显示，能更新下么？

### ISSUE THREAD

**Issue by Eraaa** [SpringCity-LaoYang/AutoXue-multiuser#44]
老大，您好！ 
环境准备中的两张图片404，能否更新下？
安装Appium-desktop，为了使用UiAutomator2，请将Appium设为以管理员权限启动，并赋予JDK和SDK所有权限，这步能否再详细些。
运行过程中，报错如下，这步我觉得没有配置好。
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to find an active device or emulator with OS 5.1.1. The following are available: 127.0.0.1:62001 (7.1.2)
怎么修改呢？

**Comment by SpringCity-LaoYang** [comment]
参考原作者的配置指南。https://github.com/kessil/AutoXue
