### ISSUE TITLE
程序检测app已登陆，退出重新登录后报错。

### ISSUE THREAD

**Issue by naiwenmoer1** [SpringCity-LaoYang/AutoXue-multiuser#72]
![image](https://user-images.githubusercontent.com/61962125/96141493-a7544a80-0f33-11eb-806e-da83fda85796.png)

**Comment by SpringCity-LaoYang** [comment]
配置好用户密码

**Comment by naiwenmoer1** [comment]
用户名密码是写好了的，困扰了我两天了，所有东西都重新装了一遍，一直是这个报错。

**Comment by naiwenmoer1** [comment]
已通过更新最新版本Appium解决。
